services:
  swagger.document.repository:
    class: KleijnWeb\SwaggerBundle\Document\DocumentRepository
    arguments: [%swagger.document.base_path%]

  swagger.document.parameter_ref_builder:
    class: KleijnWeb\SwaggerBundle\Document\ParameterRefBuilder