services:
  swagger.response.factory:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ResponseFactory
    arguments: [~]

  swagger.response.error.simple:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ErrorResponseFactory\SimpleErrorResponseFactory

  swagger.response.error.logref_builder:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\Error\LogRefBuilder\UniqueIdLogRefBuilder

  swagger.response.error_response_factory.simple:
    class: KleijnWeb\SwaggerBundle\EventListener\Response\ErrorResponseFactory\SimpleErrorResponseFactory