services:
  swagger.hydrator.array:
    class: KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\ArrayObjectHydrator

  swagger.hydrator.object:
    class: KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\ObjectObjectHydrator

  swagger.hydrator.jms:
    class:   KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\JmsObjectHydratorAdapter
    arguments: ['@swagger.hydrator.jms.target']

  swagger.hydrator.symfony:
    class:   KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\SymfonyObjectHydratorAdapter
    arguments: ['@swagger.hydrator.symfony.target']

  swagger.hydrator.jms.target:
    class:   JMS\ObjectHydrator\ObjectHydrator
    factory: [KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\Factory\JmsObjectHydratorFactory, factory]

  swagger.hydrator.symfony.target:
    class:   Symfony\Component\ObjectHydrator\ObjectHydrator
    factory: [KleijnWeb\SwaggerBundle\Serialize\ObjectHydrator\Factory\SymfonyObjectHydratorFactory, factory]

  swagger.hydrator.type_resolver.type_name_resolver:
    class:   KleijnWeb\SwaggerBundle\Serialize\TypeResolver\TypeNameResolver
    arguments: [%swagger.hydrator.namespace%]

  swagger.hydrator.type_resolver.class_name_resolver:
    class:   KleijnWeb\SwaggerBundle\Serialize\TypeResolver\ClassNameResolver
    arguments: [%swagger.hydrator.namespace%, '@swagger.hydrator.type_resolver.type_name_resolver']

  swagger.hydrator.type_resolver.hydrator_type_definition_map_builder:
    class:   KleijnWeb\SwaggerBundle\Serialize\TypeResolver\ObjectHydratorTypeDefinitionMapBuilder
    arguments: ['@swagger.hydrator.type_resolver.type_name_resolver', '@swagger.hydrator.type_resolver.class_name_resolver']
