imports:
  - { resource: document.yml }
  - { resource: listeners.yml }
  - { resource: request.yml }
  - { resource: response.yml }
  - { resource: serializer.yml }

services:
  swagger.route_loader:
    class: KleijnWeb\SwaggerBundle\Routing\SwaggerRouteLoader
    arguments: ['@swagger.document.repository']
    tags:
       - { name: routing.loader }
