imports:
  - { resource: document.yml }
  - { resource: listeners.yml }
  - { resource: request.yml }
  - { resource: response.yml }
  - { resource: hydrator.yml }

services:
  swagger.route_loader:
    class: KleijnWeb\SwaggerBundle\Routing\OpenApiRouteLoader
    arguments: ['@swagger.document.repository']
    tags:
       - { name: routing.loader }
