services:
  swagger.security.request_voter_listener:
    class: KleijnWeb\SwaggerBundle\Security\AuthorizationCheckerRequestListener
    arguments: ['@swagger.description.repository', '@security.token_storage',  '@security.authorization_checker', '%swagger.match_unsecured%' ]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7 }

  swagger.security.listener.request_authorization:
    class: KleijnWeb\SwaggerBundle\Security\RequestAuthorizationListener
    arguments: ['@security.authorization_checker' ]
    public: false

  swagger.security.provider.noop:
    class: KleijnWeb\SwaggerBundle\Security\NoopProvider
    public: false